### PR TITLE
Adds Require session parameter

### PR DESCRIPTION
**Pull request by alexbaeza**
### Change description ###

Allows module to build subscription with sessions turned on.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

### CODE REVIEW

**Review by iguannago — APPROVED** [review]

**Review by adusumillipraveen — APPROVED** [review]

**Review by adusumillipraveen — COMMENTED** [review]
can u also contribute to this branch https://github.com/hmcts/terraform-module-servicebus-subscription/tree/servicebus_subscription_tf , so they are aligned

**Comment by alexbaeza** [comment]
> can u also contribute to this branch https://github.com/hmcts/terraform-module-servicebus-subscription/tree/servicebus_subscription_tf , so they are aligned

Hi @adusumillipraveen , the other branch includes a refactor and the template json is no longer needed could you check this PR https://github.com/hmcts/terraform-module-servicebus-subscription/pull/12/files
To make sure it is as intended :)

Thank you

**Comment by adusumillipraveen** [comment]
> > can u also contribute to this branch https://github.com/hmcts/terraform-module-servicebus-subscription/tree/servicebus_subscription_tf , so they are aligned
> 
> Hi @adusumillipraveen , the other branch includes a refactor and the template json is no longer needed could you check this PR https://github.com/hmcts/terraform-module-servicebus-subscription/pull/12/files
> To make sure it is as intended :)
> 
> Thank you

Yes, this will be rolled out soon and your subscription will be broken without that change included.

**Comment by alexbaeza** [comment]
> > > can u also contribute to this branch https://github.com/hmcts/terraform-module-servicebus-subscription/tree/servicebus_subscription_tf , so they are aligned
> > 
> > 
> > Hi @adusumillipraveen , the other branch includes a refactor and the template json is no longer needed could you check this PR https://github.com/hmcts/terraform-module-servicebus-subscription/pull/12/files
> > To make sure it is as intended :)
> > Thank you
> 
> Yes, this will be rolled out soon and your subscription will be broken without that change included.

Thank you

**Pull request merged**
